# Generated by Django 2.2.7 on 2019-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='color',
            field=models.CharField(default='#0E8789', max_length=20),
        ),
    ]
