# Generated by Django 2.2.7 on 2019-11-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_lesson_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject'),
        ),
    ]
